### ISSUE TITLE
[Feature] support `go install`-based installation

### ISSUE THREAD

**Issue by orpheuslummis** [ekalinin/github-markdown-toc.go#34]
**Is your feature request related to a problem? Please describe.**
New standard in Go is to be able to install executables directly with `go install`

**Describe the solution you'd like**
- [ ] `go install https://github.com/ekalinin/github-markdown-toc.go ...` 
- [ ] update README in light of it

**Comment by KEINOS** [comment]
Since `gh-md-toc` is already compatible with `go.mod`, the `go install` must include the main package path in `/mcd/gh-md-toc` and the version of the application being followed.

The below command worked for me. (GO version go1.19 linux/amd64)

```bash
go install github.com/ekalinin/github-markdown-toc.go/cmd/gh-md-toc@latest
```

For reproducibility here's the sample on Docker.

```shellsession
$ docker run --rm -it golang:alpine /bin/sh
/go # cd

~ # go install github.com/ekalinin/github-markdown-toc.go/cmd/gh-md-toc@latest
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.4
go: downloading github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: downloading github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf

~ # gh-md-toc --version
1.2.0

~ # go version
go version go1.19 linux/amd64
```

- Ref: [Compile and install packages and dependencies](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) | go command @ pkg.go.dev

**Comment by KEINOS** [comment]
@orpheuslummis

Nothing is better than a better document. I pull-requested how to `go install` in the README.md @ PR #37.

**Comment by KEINOS** [comment]
@orpheuslummis 

The PR #37 has been merged! :tada: If this fits your needs, please close the issue. 👍

**Comment by orpheuslummis** [comment]
great. thank you @KEINOS !
