### ISSUE TITLE
Your code is completely broken now

### ISSUE THREAD

**Issue by CaledoniaProject** [ekalinin/github-markdown-toc.go#48]
I've installed the latest version with go get and it won't work with any files, e.g

```
gh-md-toc https://github.com/aminb/rust-for-c/blob/master/hello_world/README.md
```

What was changed recently? It's completely broken now.

**Comment by cgrindel** [comment]
If it is the same issue that I ran into, it is due to the fact that the rendered HTML from GitHub can and does change slightly. The current implementation uses regex to find the anchor info. I submitted a PR (#38) switching to use true HTML parsing. Feel free to download and build from that branch. Alternatively, it looks like #46 was submitted to adjust the regex.

**Comment by CaledoniaProject** [comment]
I've rolled back to the shell script version, not sure why that worked

**Comment by ekalinin** [comment]
Should be fixed in the last release:
- https://github.com/ekalinin/github-markdown-toc.go/releases/tag/v1.3.0
